[package]
name = "uni"
version = "0.1.0"
edition = "2024"

[dependencies]
tempfile = "3"  
zip = "0.6"
clap = { version = "4", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
directories = "5.0"