name: Release

on:
  push:
    tags: ["v*.*.*"]            # only runs for version tags

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            ext: ""
          - os: macos-latest
            target: x86_64-apple-darwin
            ext: ""
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            ext: ".exe"
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: ${{ matrix.target }}
        override: true

    - name: Build
      run: cargo build --locked --release --target ${{ matrix.target }}

    - name: Package binary
      run: |
        bin_name=yourapp${{ matrix.ext }}
        mkdir dist
        cp target/${{ matrix.target }}/release/$bin_name dist/
        cd dist
        tar -czf ${{ github.event.repository.name }}-${{ matrix.target }}.tar.gz $bin_name

    - name: Upload to the GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        files: dist/*
